version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      php-dependencies:
        update-types:
          - "minor"
          - "patch"
