-- Fix TYPO3 TypoScript Template setup

-- Create root template record
INSERT INTO sys_template (uid, pid, title, sitetitle, root, clear, include_static_file, constants, config, description, basedOn, includeStaticAfterBasedOn, tstamp, crdate, cruser_id) VALUES 
(1, 1, 'Main Template', 'pixelcoda TYPO3 Development', 1, 3, 'EXT:fluid_styled_content/Configuration/TypoScript/,EXT:fluid_styled_content/Configuration/TypoScript/Styling/,EXT:pixelcoda_search/Configuration/TypoScript/', 
'# Basic TYPO3 Configuration
config {
  doctype = html5
  removeDefaultJS = 0
  admPanel = 1
  debug = 0
  cache_period = 86400
  sendCacheHeaders = 1
  sys_language_uid = 0
  language = en
  locale_all = en_US.UTF-8
  htmlTag_langKey = en
}

# Page configuration
page = PAGE
page {
  typeNum = 0
  shortcutIcon = EXT:backend/Resources/Public/Icons/favicon.ico
}

# pixelcoda Search Configuration  
plugin.tx_pixelcodasearch_search {
  settings {
    mode = classic
    resultsPerPage = 10
    enableSuggestions = 1
    enableAsk = 1
    collections = pages,news
    template = Default
  }
}',
'page = PAGE
page {
  10 = FLUIDTEMPLATE
  10 {
    templateName = TEXT
    templateName.stdWrap.cObject = CASE
    templateName.stdWrap.cObject {
      key.data = pagelayout
      default = TEXT
      default.value = Default
    }
    
    templateRootPaths {
      0 = EXT:fluid_styled_content/Resources/Private/Templates/Page/
      10 = fileadmin/templates/
    }
    
    partialRootPaths {
      0 = EXT:fluid_styled_content/Resources/Private/Partials/Page/
      10 = fileadmin/partials/
    }
    
    layoutRootPaths {
      0 = EXT:fluid_styled_content/Resources/Private/Layouts/Page/
      10 = fileadmin/layouts/
    }
    
    variables {
      content < styles.content.get
      contentMain < styles.content.get
    }
  }
  
  meta {
    viewport = width=device-width, initial-scale=1
    robots = index,follow
    apple-mobile-web-app-capable = no
    description.field = description
    description.ifEmpty = pixelcoda TYPO3 Development Site
    keywords.field = keywords
    keywords.ifEmpty = pixelcoda, search, TYPO3, AI
  }
  
  headerData {
    10 = TEXT
    10.value = <title>pixelcoda TYPO3 Development</title>
  }
}

# Content configuration
styles.content.get = CONTENT
styles.content.get {
  table = tt_content
  select {
    orderBy = sorting
    where = {#colPos}=0
  }
}',
'Main TypoScript template for pixelcoda TYPO3 development site',
'',
0,
UNIX_TIMESTAMP(),
UNIX_TIMESTAMP(),
1) ON DUPLICATE KEY UPDATE 
title = VALUES(title),
config = VALUES(config),
constants = VALUES(constants),
tstamp = UNIX_TIMESTAMP();

-- Update site configuration to use correct base URL
UPDATE sys_site SET base = '/' WHERE identifier LIKE 'autogenerated%';

-- Ensure pages have proper slugs
UPDATE pages SET slug = '/' WHERE uid = 1 AND slug != '/';
UPDATE pages SET slug = '/about' WHERE uid = 2 AND (slug IS NULL OR slug = '');
UPDATE pages SET slug = '/products' WHERE uid = 3 AND (slug IS NULL OR slug = '');
UPDATE pages SET slug = '/news' WHERE uid = 4 AND (slug IS NULL OR slug = '');
UPDATE pages SET slug = '/contact' WHERE uid = 5 AND (slug IS NULL OR slug = '');
UPDATE pages SET slug = '/search' WHERE uid = 6 AND (slug IS NULL OR slug = '');
