<?php
return [
    'packages' => [
        'core' => ['packagePath' => 'typo3/sysext/core/'],
        'backend' => ['packagePath' => 'typo3/sysext/backend/'],
        'frontend' => ['packagePath' => 'typo3/sysext/frontend/'],
        'extbase' => ['packagePath' => 'typo3/sysext/extbase/'],
        'fluid' => ['packagePath' => 'typo3/sysext/fluid/'],
        'install' => ['packagePath' => 'typo3/sysext/install/'],
        'recordlist' => ['packagePath' => 'typo3/sysext/recordlist/'],
        'setup' => ['packagePath' => 'typo3/sysext/setup/'],
        'rte_ckeditor' => ['packagePath' => 'typo3/sysext/rte_ckeditor/'],
        'fluid_styled_content' => ['packagePath' => 'typo3/sysext/fluid_styled_content/'],
        'tstemplate' => ['packagePath' => 'typo3/sysext/tstemplate/'],
        'felogin' => ['packagePath' => 'typo3/sysext/felogin/'],
        'form' => ['packagePath' => 'typo3/sysext/form/'],
        'scheduler' => ['packagePath' => 'typo3/sysext/scheduler/'],
        'extensionmanager' => ['packagePath' => 'typo3/sysext/extensionmanager/'],
        'filelist' => ['packagePath' => 'typo3/sysext/filelist/'],
        'info' => ['packagePath' => 'typo3/sysext/info/'],
        'lowlevel' => ['packagePath' => 'typo3/sysext/lowlevel/'],
        'reports' => ['packagePath' => 'typo3/sysext/reports/'],
        'sys_note' => ['packagePath' => 'typo3/sysext/sys_note/'],
        't3editor' => ['packagePath' => 'typo3/sysext/t3editor/'],
        'viewpage' => ['packagePath' => 'typo3/sysext/viewpage/'],
        'dashboard' => ['packagePath' => 'typo3/sysext/dashboard/'],
        'redirects' => ['packagePath' => 'typo3/sysext/redirects/'],
        'seo' => ['packagePath' => 'typo3/sysext/seo/'],
        // HEADLESS DISABLED FOR STANDARD MODE
        // 'headless' => ['packagePath' => 'vendor/friendsoftypo3/headless/'],
        'news' => ['packagePath' => 'vendor/georgringer/news/'],
        'pixelcoda_search' => ['packagePath' => 'typo3conf/ext/pixelcoda_search/'],
        'site_package' => ['packagePath' => 'typo3conf/ext/site_package/'],
    ],
    'version' => 5,
];
